---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create parameters group for MySQL
      rds_param_group:
        region: "{{ m_region }}"
        state: present
        name: geonetwork-custom
        description: "Parametros para el funcionamiento de geonetwork"
        engine: 'mysql5.6'
        params:
          lower_case_table_names: "1"

    - name: Provisioning of database
      rds:
        #wait: true
        command: create
        instance_name: "{{ db_instance_name }}"
        region: "{{ m_region }}"
        db_name: "{{ db_db_name }}"
        db_engine: MySQL
        instance_type: "{{ db_instance_type }}"
        size: "{{ db_size }}"
        parameter_group: geonetwork-custom
        username: "{{ db_username }}"
        password: "{{ db_password }}"
        tags:
          Application: geonetwork
