---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Include aws vars
      include_vars:
        file: aws/group_vars/all

- include: "aws/ec2.yml"

# wait for ec2 instances to be available
- hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Refreshing EC2 inventory cache
      shell: "python aws/inventory/ec2.py --list --refresh-cache"

    - meta: refresh_inventory

    - name: Waiting for SSH to be available on Application Server
      wait_for: port=22 host="{{ hostvars[groups['tag_Name_appserver'][0]]['ec2_public_dns_name'] }}"
      connection: local

    - name: Waiting for SSH to be available on Elasticsearch Server
      wait_for: port=22 host="{{ hostvars[groups['tag_Name_elasticsearchserver'][0]]['ec2_public_dns_name'] }}"
      connection: local

    - name: Waiting for SSH to be available on Web Server
      wait_for: port=22 host="{{ hostvars[groups['tag_Name_webserver'][0]]['ec2_public_dns_name'] }}"
      connection: local

- include: "main.yml"
